[
build
]
builder = "NIXPACKS"

[
build.nixpacksPlan.phases.setup
]
nixPkgs = ["python311"]

[
deploy
]
startCommand = "python app.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5